client:
  build: ./client
  ports:
    - "80:80"
  expose:
    - "80"
  volumes:
    - ./client:/usr/src/client
  command: sh
  tty: true

server:
  build: ./server
  command: python3 manage.py runserver 0.0.0.0:8000
  volumes:
    - ./server:/usr/src/server
  ports:
    - "8000:8000"
  links:
    - postgres
  environment:
    POSTGRES_NAME: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASS: postgres
    
postgres:
  image: postgres:9.5-alpine
  ports:
    - "5432:5432"
  expose:
    - "5432"
